### ISSUE TITLE
Update new repo URL everywhere

### ISSUE THREAD

**Issue by oceyral** [camunda-community-hub/camunda-cloud-helm#1]
Hi,

In https://github.com/camunda-community-hub/zeebe-helm/commit/af79d0cc0c7e5f575509b21c5742198abf35f1d6#diff-8bc94a3006768345d17c827c0bb5840e6e4daee6de1c2b1ea672f53f162d171dL56, the url of the chart repository was changed, but that wasn't reflected in the README here, nor in other repositories (zeebe-operate, zeebe-cluster, ...).

The old URL (helm.zeebe.io) returns 404.

**Comment by Zelldon** [comment]
I think this issue can be closed
