### ISSUE TITLE
Ingress in zeebe-full-helm doesn't work with k8s 1.22

### ISSUE THREAD

**Issue by falko** [camunda-community-hub/camunda-cloud-helm#102]
When installing `zeebe-full-helm` on k8s 1.22 the nginx ingress is crash-looping. This might be due to updates in k8s: 
https://kubernetes.io/blog/2021/07/26/update-with-ingress-nginx/

**Comment by falko** [comment]
More info:
https://kubernetes.github.io/ingress-nginx/#faq-migration-to-apiversion-networkingk8siov1
https://github.com/kubernetes/ingress-nginx#support-versions-table
https://www.nginx.com/blog/nginx-ingress-controller-version-2-0-what-you-need-to-know/

**Comment by falko** [comment]
[Operate's ingress.yaml](https://github.com/camunda-community-hub/camunda-cloud-helm/tree/main/charts/zeebe-operate-helm/templates/ingress.yaml) looks like the new version is used so I'm not sure if something else is missing or I ran an older chart version. Currently, I downgraded k8s to 1.21. So I can't test that quickly.

**Comment by falko** [comment]
`ingress-nginx` Helm Chart [4.0.1](https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/CHANGELOG.md#401) is the first one to inlcude `ingress-nginx` v1.0.0, which is the [first version compatible with k8s 1.22](https://github.com/kubernetes/ingress-nginx#support-versions-table).

**Comment by Zelldon** [comment]
We will no longer deploy a ingress controller with the charts see https://github.com/camunda-community-hub/camunda-cloud-helm/pull/150
