### ISSUE TITLE
Standalone Gateway pod 9600 endpoint returns 503 Service Unavailable

### ISSUE THREAD

**Issue by andylholloway** [camunda-community-hub/camunda-cloud-helm#11]
Hi

I recently deployed zeebe-cluster-helm chart version 0.0.88 and as part of my testing noticed that the gateway service exposes an endpoint on port 9600, which seems to always return:

_503 Service Unavailable
upstream connect error or disconnect/reset before headers. reset reason: connection failure_

I know this endpoint is exposed by the Zeebe pods and used by Kubernetes to check when the pod is ready, but in the gateway deployment I don't think the 9600 endpoint is used and the gateway pod seems to be ready and working, despite the 503 error. 

So, is the 9600 endpoint required on the gateway pod and if yes, what might be causing the 503 error?

I tested this endpoint by calling :9600/ready, perhaps for the gateway this endpoint is invalid?

I have checked the logs, which I can provide if it helps, but they simply report that a 503 Service Unavailable error was returned.

Worth mentioning... The reason I say the gateway pod is working is because when I request the Topology I get the following response:
```
{
  "brokers": [
    {
      "partitions": [],
      "nodeId": 0,
      "host": "workflow-engine-zeebe-0.workflow-engine-zeebe.ah-playground.svc.cluster.local",
      "port": 26501
    }
  ],
  "clusterSize": 1,
  "partitionsCount": 1,
  "replicationFactor": 1
}
```
So I have assumed the standalone gateway is talking to the Zeebe Cluster.

config:
Zeebe version 0.22.1

Zeebe Cluster:
clusterSize: 1
partitionCount: 1
replicationFactor: 1

ES
replicas: 1

Thanks
Andy

**Comment by Zelldon** [comment]
I feel this issue is a bit outdate, please reopen if you have still the issue
