### ISSUE TITLE
zeebe installation fails

### ISSUE THREAD

**Issue by sandygmaharaj** [camunda-community-hub/camunda-cloud-helm#117]
I am trying to install zeebe via helm charts in a separate namespace, the same fails. I have capture the debug logs from helm command as below:

$ helm install zeebe zeebe/zeebe-full-helm -n zeebe --debug
install.go:178: [debug] Original chart version: ""
install.go:199: [debug] CHART PATH: /home/edgeprov/.cache/helm/repository/zeebe-full-helm-1.3.1.tgz

client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD alertmanagerconfigs.monitoring.coreos.com is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD alertmanagers.monitoring.coreos.com is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD podmonitors.monitoring.coreos.com is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD probes.monitoring.coreos.com is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD prometheuses.monitoring.coreos.com is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD prometheusrules.monitoring.coreos.com is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD servicemonitors.monitoring.coreos.com is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:151: [debug] CRD thanosrulers.monitoring.coreos.com is already present. Skipping.
W0117 18:44:32.951595 1150858 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
client.go:299: [debug] Starting delete for "zeebe-ingress-nginx-admission" ServiceAccount
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "zeebe-ingress-nginx-admission" ClusterRole
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "zeebe-ingress-nginx-admission" ClusterRoleBinding
client.go:328: [debug] clusterrolebindings.rbac.authorization.k8s.io "zeebe-ingress-nginx-admission" not found
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "zeebe-ingress-nginx-admission" Role
client.go:328: [debug] roles.rbac.authorization.k8s.io "zeebe-ingress-nginx-admission" not found
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "zeebe-ingress-nginx-admission" RoleBinding
client.go:328: [debug] rolebindings.rbac.authorization.k8s.io "zeebe-ingress-nginx-admission" not found
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "zeebe-ingress-nginx-admission-create" Job
client.go:328: [debug] jobs.batch "zeebe-ingress-nginx-admission-create" not found
client.go:128: [debug] creating 1 resource(s)
client.go:528: [debug] Watching for changes to Job zeebe-ingress-nginx-admission-create with timeout of 5m0s
client.go:556: [debug] Add/Modify event for zeebe-ingress-nginx-admission-create: ADDED
client.go:595: [debug] zeebe-ingress-nginx-admission-create: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
Error: INSTALLATION FAILED: failed pre-install: timed out waiting for the condition
helm.go:88: [debug] failed pre-install: timed out waiting for the condition
INSTALLATION FAILED
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:127
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.2.1/command.go:902
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
        runtime/proc.go:225
runtime.goexit
        runtime/asm_amd64.s:1371

**Comment by Zelldon** [comment]
Please try with the new chart https://github.com/camunda-community-hub/camunda-cloud-helm/tree/main/charts/ccsm-helm
