### ISSUE TITLE
Add a section about how to contribute in the readme

### ISSUE THREAD

**Issue by Hafflgav** [camunda-community-hub/camunda-cloud-helm#134]
As a last chapter it would be awesome to see some kind of contribution guide/ section in the readme. 
Maybe you could just link one created by @celanthe. I just found this page [here](https://camunda.com/developers/how-to-contribute/ ). Nevertheless, Camunda Platform deals with it separately in their [GitHub Repository](https://github.com/camunda/camunda-bpm-platform/blob/master/CONTRIBUTING.md).

**Comment by celanthe** [comment]
Hi @Hafflgav and @Zelldon  -- Feel free to use the CoC listed at https://github.com/camunda-community-hub/community/blob/main/CONTRIBUTING.MD or the one at https://github.com/camunda-cloud/camunda-cloud-documentation/blob/master/CONTRIBUTING.MD

**Comment by Zelldon** [comment]
Add documentation guidelines as well https://github.com/camunda-community-hub/camunda-cloud-helm/pull/141#pullrequestreview-867555316

**Comment by Zelldon** [comment]
I added https://github.com/camunda-community-hub/camunda-cloud-helm/blob/main/CONTRIBUTING.md and https://github.com/camunda-community-hub/camunda-cloud-helm/blob/main/CODE_OF_CONDUCT.md
