### ISSUE TITLE
Support non-root deployments

### ISSUE THREAD

**Issue by npepinpe** [camunda-community-hub/camunda-cloud-helm#15]
**Description**

It's not currently possible to support non-root deployments with the Helm charts. In order to do so, we need to:

1. Allow users to configure the StatefulSet's `.spec.template.securityContext` so users can add `runAsUser`, `runAsGroup`, and `fsGroup` (and set it to 1000 as recommended value)
1. Update the volumes section and set the `defaultMode` of the `config` volume to `0777` instead of `0744`.

**Comment by sherry-ummen** [comment]
This is an important feature for us :(

**Comment by Zelldon** [comment]
Feel free to create an PR

**Comment by sherry-ummen** [comment]
Thanks. here you go: https://github.com/camunda-community-hub/camunda-cloud-helm/pull/63

**Comment by Zelldon** [comment]
As written here https://github.com/camunda-community-hub/camunda-cloud-helm/pull/63#pullrequestreview-796174504

> It seems in the StatefulSetSepc the securityContext can be added on two places. On the podSpec https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#podspec-v1-core where you have added it now and on the container level https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#container-v1-core which will overwrite then the podSpec SecurityContext, this is what we currently have.
> 
> I think this is also used by our benchmarks, I totally forgot about that sorry! You can see an example of it here https://github.com/camunda-cloud/zeebe/blob/develop/benchmarks/setup/default/zeebe-values.yaml#L14-L16

I think the current podSecurityContext is enough I will add it to the readme
