### ISSUE TITLE
Add example how to configure the helm chart / Zeebe

### ISSUE THREAD

**Issue by berndruecker** [camunda-community-hub/camunda-cloud-helm#2]
The config parameters are described in a bullet point list currently, but I personally would love to see an example file for the stupids (like me) who are not completely sure how to apply them exactly.

As you can see here I spontaneously messed it up: https://github.com/berndruecker/kafka-connect-zeebe-benchmark/pull/2/files ;-)

**Comment by Zelldon** [comment]
for that we have https://github.com/camunda-community-hub/zeebe-helm-profiles
