### ISSUE TITLE
`zeebe-operate-helm`: Ingress apiVersion `networking.k8s.io/v1` is not available in K8S < 1.19.0

### ISSUE THREAD

**Issue by Hermsi1337** [camunda-community-hub/camunda-cloud-helm#25]
It's not possible to deploy the `zeebe-operate-helm`-chart to K8S-Clusters with a version `< 1.19.0` due to an incompatibility with the `ingress`'s `apiVersion`.

Is this by design because you don't want to support K8S-versions which are `EOL` with this chart?  
Otherwise I'd like to provide a "fix" for that by adjusting the `ingress.yaml` as it is created per default by `$ helm create chart`:

```yaml
# [...]
{{- if .Values.ingress.enabled -}}
# [...]
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
# [...]
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
# [...]
```

```shell
$ k version
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"68b4e26caf6ede7af577db4af62fb405b4dd47e6", GitTreeState:"clean", BuildDate:"2021-03-18T00:54:02Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

$ helm upgrade --install --namespace ${K8S_NAMESPACE} camundacloud/zeebe-operate-helm .
Error: UPGRADE FAILED: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1"
```

**Comment by Zelldon** [comment]
Hey @Hermsi1337 thanks for reporting! Yes in general I wanted to avoid such if else squabbling. Recently I decided for supporting 1.19+ https://github.com/camunda-community-hub/camunda-cloud-helm/issues/23, as you mentioned it already reached EOL.

Is there a specific reason why you need to use 1.18? Do you think it is worth to support it ? I'm new to this :)

**Comment by Hermsi1337** [comment]
Hey @Zelldon,

many thanks for your fast reply.

Woops... seems like I've missed the issue you mentioned, sorry for that >.<

Actually there is no specific reason (for us) to use Kubernetes 1.18 and I don't think it's _required_ to support old versions with the `zeebe-operate-helm`-chart.  
I just stumbled across the incompatibility with k8s < `1.19` and was curious if it's by design or someone "missed it" wenn creating the chart.

We're totally fine with the chart being only compatible with k8s-versions >= `1.19` since we're using a more current version of k8s in production.  
Nevertheless, it would be a nice2have if the chart could also be used for older k8s-versions - imho.


PS:

To all the wisdom seekers facing the same "problem" and finding this issue:  
Take a deep breath and update your cluster. Your future self will thank your for that :3

**Comment by Zelldon** [comment]
Thanks for sharing @Hermsi1337 then I will keep as it is for now. I will close this issue, if there are new complains / requests for that feature we can reopen the issue :) and discuss this further.

Thanks and greets
Chris
