### ISSUE TITLE
resource part ist not taken from values.yaml

### ISSUE THREAD

**Issue by milanhorvath** [camunda-community-hub/camunda-cloud-helm#5]
i have tried the zeebe-operate helm chart and wanted to override the resource part like it is possible in zeebe-cluster-helm. But here the resource part is hardcoded written in deployment.yaml so it is not possible. Would be good to have it defined the same way like in https://github.com/zeebe-io/zeebe-cluster-helm/blob/master/zeebe-cluster/templates/statefulset.yaml

**Comment by Zelldon** [comment]
supersed by https://github.com/camunda-community-hub/camunda-cloud-helm/issues/27
