### ISSUE TITLE
Expose Prometheus via Ingress with Zeebe Full Helm Chart

### ISSUE THREAD

**Issue by salaboy** [camunda-community-hub/camunda-cloud-helm#8]
Right now Prometheus can be deployed with a Zeebe Cluster, but in order to access grafana you need to port forward to it, this can be simplified by enabling the ingress in the prometheus chart and making sure that our Ingress Controller expose the right paths. This has proved to be challenging and time-consuming but I am sure that it can be done.

**Comment by Zelldon** [comment]
see currently no need for it. Most of the time prometheus is deployed externally, via operator for example.
