### ISSUE TITLE
Add extra container and init container values

### ISSUE THREAD

**Issue by npepinpe** [camunda-community-hub/camunda-cloud-helm#9]
When using the Helm charts to demo or test something, it's sometimes useful to be able to inject sidecar containers, or extra init containers. Some operators (e.g. linkerd) do this for you through annotations, others require you to do this yourself (e.g. Jaeger - they support annotations as well, but only on deployments for whatever reason).

AT:

- add `extraAnnotations` value to allow specifying annotations for pods
- add `extraContainers` value to allow specifying sidecar containers for pods
- add `extraInitContainers` value to allow specifying additional init containers for pods (e.g. testing migration script, for example)
- add `extraVolumes` and `extraVolumeMounts` to allow injecting/overwriting files during deployment

At the moment I really only care to scope all of these for Zeebe, not sure if it makes sense to have these for other services; some of them might even have partial support already.

**NOTE**: see some examples [here](https://github.com/helm/charts/pull/3983) and [here](https://github.com/helm/charts/pull/5887), and some discussion [here](https://github.com/helm/charts/issues/4283)

**Comment by Zelldon** [comment]
I assume this is still the case @npepinpe

**Comment by npepinpe** [comment]
I think it's a common use case, but nothing urgent.
